# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               L/D
tagline:             'Online ground school resource'
description:         'A concise yet comprehensive review of topics related to the private pilot oral and written exam.'
url:                 http://ericburlingame.com/
baseurl:             /l-over-d/

defaults:
  - scope:
      path: ""
    values:
      image: true

# About/contact
author:
  name:              Eric Burlingame
  url:               https://ericburlingame.com/
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
